const f =()=>{
try{
    let a=0;
    console.log(program)
    console.log("program run successfully")
    return
}
catch(err){
    console.log("this is an error")
}
finally{
    console.log("i am a good boy")
}
}
f()

console.log("End")